### ISSUE TITLE
integration tests on production is not working

### ISSUE THREAD

**Issue by laljikanjareeya** [cloudspannerecosystem/dotnet-spanner-entity-framework#61]
It seems like two issue:
1. GitHub Actions
2. Parallel test execution

Running integration test sequentially, it finishes after 16 mins locally.
In case of parallel execution, it goes into never ending process.

//cc
@olavloite

**Comment by olavloite** [comment]
It might very well be that reducing the number of tests that are allowed to run in parallel will also help (instead of bringing it completely back to 1 by disabling parallel execution).

**Comment by olavloite** [comment]
This has been fixed.
